event_inherited();
prepared = true;
ingrName = "Lettuce ";
type = "booster";
ing_id = 6;
hp = 0;
attack = 0;
defense = 3;
spd = 0;
special = false;
runeSprite = sLettuceRune;
classification = "vegetable";
adjective = "Green ";
chops = 10;