event_inherited();
prepared = false;
ingrName = "Onion ";
type = "booster";
ing_id = 3;
hp = 0;
attack = 5;
defense = 0;
spd = 0;
special = false;
runeSprite = sOnionRune;
classification = "vegetable";
adjective = "Onion ";